spring:
  application:
    name: eureka-client

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true